# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    build:
      args:
        - GITHUB_TOKEN=${ACTIONS_BOT_TOKEN:?}
      context: .
    volumes:
      - .:/work
    working_dir: /work
    command: spec
  ci:
    build:
      args:
        - GITHUB_TOKEN=${ACTIONS_BOT_TOKEN:?}
      context: containers/ci
    volumes:
      - .:/work
    working_dir: /work

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  licensing:
    build:
      context: containers/licensing
      args:
        - GITHUB_TOKEN=${ACTIONS_BOT_TOKEN:?}
    volumes:
      - .:/work
    working_dir: /work
