# Use root/example as user/password credentials
version: '3.1'

services:
  app:
    image: golang:1.18rc1
    volumes:
      - .:/work
    working_dir: /work
    environment:
      - GITHUB_TOKEN=${ACTIONS_BOT_TOKEN:?}

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  licensing:
    build:
      context: containers/licensing
    volumes:
      - .:/work
    working_dir: /work
    environment:
      - GITHUB_TOKEN=${ACTIONS_BOT_TOKEN:?}
